// Migrations are generated by Drizzle Kit and stored in /migrations directory
// This file exports migration utilities

import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { getDb } from './db';
import * as path from 'path';

export async function runMigrations() {
  const db = getDb();
  const migrationsPath = path.join(__dirname, '../migrations');
  
  console.log('Running migrations from:', migrationsPath);
  
  migrate(db, { migrationsFolder: migrationsPath });
  
  console.log('Migrations completed successfully');
}
